name = "DynamicGrids"
uuid = "a5dba43e-3abc-5203-bfc5-584ca68d3f5b"
authors = ["Rafael Schouten <rafaelschouten@gmail.com>"]
version = "0.21.4"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FreeTypeAbstraction = "663a7486-cb36-511b-a19d-713bb74d65c9"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModelParameters = "4744a3fa-6c31-4707-899e-a3298e4618ad"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnicodeGraphics = "ebadf6b4-db70-5817-83da-4a19ad584e34"

[compat]
Adapt = "2, 3"
Colors = "0.9, 0.10, 0.11, 0.12"
ConstructionBase = "1"
Crayons = "4"
DimensionalData = "0.19, 0.20, 0.21, 0.22, 0.23"
DocStringExtensions = "0.8, 0.9"
FileIO = "1"
FreeTypeAbstraction = "^0.6.5, 0.8, 0.9, 0.10"
KernelAbstractions = "0.6, 0.7, 0.8"
ModelParameters = "0.3"
OffsetArrays = "0.11, 1"
Reexport = "0.2, 1.0"
Requires = "1"
Setfield = "0.6, 0.7, 0.8, 1"
StaticArrays = "0.12, 1"
UnicodeGraphics = "0.1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDAKernels = "72cfdca4-0801-4ab0-bf6a-d52aa10adc57"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["Aqua", "BenchmarkTools", "ColorSchemes", "CUDAKernels", "FixedPointNumbers", "ImageMagick", "SafeTestsets", "StaticArrays", "Unitful"]
